
package com.itsolutioncenter.forms;

import com.itsolutioncenter.dao.DatabaseManager;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad Shafiq Amiri
 */
public class AttendanceForm extends javax.swing.JInternalFrame {
    private DatabaseManager dbManager=DatabaseManager.getInstance();
    private DefaultTableModel model=new DefaultTableModel();
private String query,courseCode,status;
private int row;
private ResultSet rs;
    /**
     * Creates new form AttendanceForm
     */
    public AttendanceForm() {
        initComponents();
        rdbGroup.add(rdbAbsent);
        rdbGroup.add(rdbPresent);
        rdbGroup.add(rdbExcused);
        loadCourses();
        loadAttendance();
    }
    private void loadAttendance ()
    {
        query="SELECT course_enrollments.enrollment_id," +
   " students.full_name, attendance.`status`," +
   " attendance.check_in_time, attendance.remarks, courses.course_name" +
   " FROM attendance"+
   " INNER JOIN course_enrollments ON course_enrollments.enrollment_id = attendance.enrollment_id" +
   " INNER JOIN courses ON courses.course_id = course_enrollments.course_id" +
   " INNER JOIN students ON students.student_id = course_enrollments.student_id";
        model=dbManager.getTableModel(query, tblAttendance);
        tblAttendance.setModel(model);
    }
    private void loadCourses()
    {
        cmbCourse.removeAllItems();
        cmbCourse.addItem("-- Select Course --");
        query="select course_code, course_name from courses";  
        try{
            List<Map<String,Object>>courseName=dbManager.select(query);
            for(Map<String,Object>course:courseName){
            cmbCourse.addItem(course.get("course_code").toString()); //+" - "+course.get("course_name");
        }
//          
//         rs=DatabaseManager.executeSimpleQuery(query);
//         while(rs.next())
//         {
//             cmbCourse.addItem(rs.getString("course_code"));//+" - "+rs.getString("course_name"));
//         }
        }catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
        
    }
    private void loadSelectedCourseAttendance()
    {
        courseCode=cmbCourse.getSelectedItem().toString();
       //StringBuilder s=new StringBuilder(courseCode);
        
        query="SELECT course_enrollments.enrollment_id," +
   " students.full_name, attendance.`status`," +
   " attendance.check_in_time, attendance.remarks, courses.course_name" +
   " FROM attendance"+
   " INNER JOIN course_enrollments ON course_enrollments.enrollment_id = attendance.enrollment_id" +
   " INNER JOIN courses ON courses.course_id = course_enrollments.course_id" +
   " INNER JOIN students ON students.student_id = course_enrollments.student_id"+
        " AND course_enrollments.enrollment_id = attendance.enrollment_id"+
                " where course_code='"+courseCode+"'";
        model=dbManager.getTableModel(query, tblAttendance);
        tblAttendance.setModel(model);
    }
    private void applyStatus()
    {
    row=tblAttendance.getSelectedRow();
    status="Present";
    if(rdbAbsent.isSelected())status="Absent";
        else if(rdbExcused.isSelected())status="Excused";
    for(int i=0;i<model.getRowCount();i++){
        model.setValueAt(status, row, 2);
    }
        
        
    
    }
    private void setCurrentTime() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        String currentTime = timeFormat.format(new java.util.Date());
       row=tblAttendance.getSelectedRow();
        for (int i = 0; i < model.getRowCount(); i++) {
           status = model.getValueAt(i, 2).toString();
            if (status.equals("Present") || status.equals("Late")) {
                model.setValueAt(currentTime, row, 3);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        btnLoadStudents = new javax.swing.JButton();
        btnSaveAttendance = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rdbPresent = new javax.swing.JRadioButton();
        rdbAbsent = new javax.swing.JRadioButton();
        rdbExcused = new javax.swing.JRadioButton();
        btnApplySelected = new javax.swing.JButton();
        btnSetCurrentTime = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Attendance Form");
        setToolTipText("");

        jLabel1.setText("Select Course:");

        jLabel2.setText("Attendance Date:");

        dateChooser.setDateFormatString("dd-MM-yyyy");

        btnLoadStudents.setText("Load Students");
        btnLoadStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadStudentsActionPerformed(evt);
            }
        });

        btnSaveAttendance.setText("Save Attendance");

        btnGenerateReport.setText("Generate Report");

        jLabel3.setText("Status:");

        rdbPresent.setSelected(true);
        rdbPresent.setText("Present");

        rdbAbsent.setText("Absent");

        rdbExcused.setText("Excused");

        btnApplySelected.setText("Apply to Selected");
        btnApplySelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplySelectedActionPerformed(evt);
            }
        });

        btnSetCurrentTime.setText("Set Current Time");
        btnSetCurrentTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetCurrentTimeActionPerformed(evt);
            }
        });

        jButton1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(rdbPresent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbAbsent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbExcused)
                        .addGap(18, 18, 18)
                        .addComponent(btnApplySelected)
                        .addGap(56, 56, 56)
                        .addComponent(btnSaveAttendance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerateReport)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoadStudents)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSetCurrentTime)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoadStudents))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSetCurrentTime)
                            .addComponent(jButton1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdbPresent)
                            .addComponent(rdbAbsent)
                            .addComponent(rdbExcused)
                            .addComponent(btnApplySelected))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveAttendance)
                            .addComponent(btnGenerateReport))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Student Name", "Status", "Check-in Time", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAttendance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAttendance.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAttendance);
        tblAttendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblAttendance.getColumnModel().getColumnCount() > 0) {
            tblAttendance.getColumnModel().getColumn(0).setResizable(false);
            tblAttendance.getColumnModel().getColumn(1).setResizable(false);
            tblAttendance.getColumnModel().getColumn(2).setResizable(false);
            tblAttendance.getColumnModel().getColumn(3).setResizable(false);
            tblAttendance.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadStudentsActionPerformed
        loadSelectedCourseAttendance();
    }//GEN-LAST:event_btnLoadStudentsActionPerformed

    private void btnApplySelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplySelectedActionPerformed
        applyStatus();
    }//GEN-LAST:event_btnApplySelectedActionPerformed

    private void btnSetCurrentTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCurrentTimeActionPerformed
        setCurrentTime();
    }//GEN-LAST:event_btnSetCurrentTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplySelected;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLoadStudents;
    private javax.swing.JButton btnSaveAttendance;
    private javax.swing.JButton btnSetCurrentTime;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCourse;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbAbsent;
    private javax.swing.JRadioButton rdbExcused;
    private javax.swing.ButtonGroup rdbGroup;
    private javax.swing.JRadioButton rdbPresent;
    private javax.swing.JTable tblAttendance;
    // End of variables declaration//GEN-END:variables
}
