package com.itsolutioncenter.forms;

import com.itsolutioncenter.dao.DatabaseManager;
import com.itsolutioncenter.model.Permission;
import com.itsolutioncenter.model.User;
import com.itsolutioncenter.service.UserService;
import com.itsolutioncenter.util.Validator;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Admin
 */
public class ChangePasswordForm extends javax.swing.JInternalFrame {
private User currentUser;
private int userID;
private DatabaseManager dbManager=DatabaseManager.getInstance();
private String currentPassword,newPassword,confirmPassword;
private UserService userservice=new UserService();
    /**
     * Creates new form frmChangePassword
     * @param user
     */
    public ChangePasswordForm(User user,Permission permissionService)
    {
        initComponents();
        this.currentUser=new User();
        this.currentUser.setUserId(user.getUserId());
        this.currentUser.setUsername(user.getUsername());
        this.currentUser.setFullName(user.getFullName());
        this.currentUser.setPasswordHash(user.getPasswordHash());
        this.currentUser.setRole(user.getRole());
        userID=user.getUserId();
        lblUser.setText("[ "+user.getUsername()+" ]");  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCurrentPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtConfirmedPass = new javax.swing.JPasswordField();
        btnChangePassword = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Change Password Form");
        setToolTipText("Here you can change your current password");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Current Password:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password:");

        txtCurrentPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCurrentPassKeyPressed(evt);
            }
        });

        txtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPassKeyPressed(evt);
            }
        });

        txtConfirmedPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmedPassKeyPressed(evt);
            }
        });

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Current User:");

        lblUser.setText("[user]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewPass)
                            .addComponent(txtCurrentPass)
                            .addComponent(txtConfirmedPass, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnChangePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblUser))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCurrentPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmedPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnCancel))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       clearControls();
    }//GEN-LAST:event_btnCancelActionPerformed
    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
           changePasswords();
    }//GEN-LAST:event_btnChangePasswordActionPerformed
    private void txtCurrentPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentPassKeyPressed
        txtCurrentPass.setBackground(Color.WHITE);
        txtCurrentPass.setBorder(UIManager.getBorder("TextField.border"));
        txtCurrentPass.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtCurrentPassKeyPressed

    private void txtNewPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPassKeyPressed
        txtNewPass.setBackground(Color.WHITE);
        txtNewPass.setBorder(UIManager.getBorder("TextField.border"));
        txtNewPass.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNewPassKeyPressed

    private void txtConfirmedPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmedPassKeyPressed
        txtConfirmedPass.setBackground(Color.WHITE);
        txtConfirmedPass.setBorder(UIManager.getBorder("TextField.border"));
        txtConfirmedPass.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtConfirmedPassKeyPressed
    private void clearControls()
    {
        txtCurrentPass.setText("");
        txtNewPass.setText("");
        txtConfirmedPass.setText("");
        txtCurrentPass.requestFocusInWindow();
        txtCurrentPass.setBackground(Color.WHITE);
        txtCurrentPass.setBorder(UIManager.getBorder("TextField.border"));
        txtCurrentPass.setForeground(Color.BLACK); 
        txtNewPass.requestFocusInWindow();
        txtNewPass.setBackground(Color.WHITE);
        txtNewPass.setBorder(UIManager.getBorder("TextField.border"));
        txtNewPass.setForeground(Color.BLACK); 
        txtConfirmedPass.requestFocusInWindow();
        txtConfirmedPass.setBackground(Color.WHITE);
        txtConfirmedPass.setBorder(UIManager.getBorder("TextField.border"));
        txtConfirmedPass.setForeground(Color.BLACK); 
    }
    private void changePasswords() 
    {
         newPassword = new String(txtNewPass.getPassword());
         currentPassword =new String(txtCurrentPass.getPassword());
         if(!Validator.validateRequired(txtCurrentPass,"Current Password"))
         {
         return; 
         }   
         if(!Validator.validateRequired(txtNewPass, "New Password"))
         {
           return;  
         }          
         if(!Validator.validateRequired(txtConfirmedPass, "Confirmed Password"))
         {
            return;
         }
         if(!userservice.verifyPassword(userID,currentPassword))
         {  
             JOptionPane.showMessageDialog(null, "Current Password is Incorrect!");
            txtCurrentPass.requestFocusInWindow();
            txtCurrentPass.setBackground(new Color(255,230,230));
            txtCurrentPass.setForeground(Color.red);
            txtCurrentPass.setBorder(BorderFactory.createLineBorder(Color.yellow,2));
                return;
         }
             confirmPassword = new String(txtConfirmedPass.getPassword());
         if (!Validator.isMatchedPassword(newPassword, confirmPassword,txtConfirmedPass)) {  
                return;
         }
         if(!Validator.isLengthValid(newPassword, 5, 10)){
                JOptionPane.showMessageDialog(this, "Password must be at least 5 or maximum 10 characters",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
         }
         if(userservice.changePassword(userID,currentPassword, newPassword))
         {
            JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
         }
         clearControls(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtConfirmedPass;
    private javax.swing.JPasswordField txtCurrentPass;
    private javax.swing.JPasswordField txtNewPass;
    // End of variables declaration//GEN-END:variables
}