package com.itsolutioncenter.forms;

import com.itsolutioncenter.dao.DatabaseManager;
import com.itsolutioncenter.service.InternService;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ahmad Shafiq Amiri
 */
public class InternApplicationForm extends javax.swing.JInternalFrame {
private DatabaseManager dbManager=DatabaseManager.getInstance();
private InternService internservice=new InternService();
private ResultSet rs;
private DefaultTableModel model=new DefaultTableModel();
private String query,name,email;
private int id,row;
    /**
     * Creates new form InternApplicationForm
     */
    public InternApplicationForm() {
        initComponents();
        loadInternData();
    }
    private void loadInternData()
    {
        query="select * from intern_applications";
        model=dbManager.getTableModel(query, tblInterns);
        tblInterns.setModel(model);
    }
    private void searchData() {
        String searchText=txtSearch.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter search criteria: Course ID, Course Code or Course Name");
            return;
        }
        boolean isNumeric = searchText.matches("\\d+");  
            if (isNumeric) {
                // Search by ID (numeric ID)
                id=Integer.parseInt(searchText);
                query = "select * from intern_applications where application_id = '"+id+"'";
            } else {
                // Search by username OR full name only (non-numeric)
                query= "select * from intern_applications where applicant_name LIKE '"+searchText+"' OR phone LIKE '"+searchText+"'";
            }
            model=dbManager.getTableModel(query,tblInterns);
            tblInterns.setModel(model); 
            txtSearch.setText("");
    }
   
     private void filterIntens() {
        String category = (String) cmbAppliedForFilter.getSelectedItem();
        String status = (String) cmbStatusFilter.getSelectedItem();
       
        try {
            List<Map<String, Object>> filteredInterns = internservice.getAllApplications();
           
            // Apply filters
            if (!category.equals("All Sectors")) {
                filteredInterns.removeIf(asset -> !category.equals(asset.get("applied_for")));
            }
           
            if (!status.equals("All Statuses")) {
                filteredInterns.removeIf(asset -> !status.equalsIgnoreCase((String) asset.get("status")));
            }
           
             DefaultTableModel model = (DefaultTableModel) tblInterns.getModel();
        model.setRowCount(0);
        for (Map<String, Object> application : filteredInterns) {
            model.addRow(new Object[]{
                application.get("application_id"),
                application.get("applicant_name"),
                application.get("email"),
                application.get("phone"),
                application.get("university"),
                application.get("course"),
                application.get("Qualification"),
                application.get("resume_path"),
                application.get("applied_for"),
                application.get("application_date"),
                application.get("status"),
                application.get("interview_date"),
                application.get("interview_note"),
                application.get("skills")
            });
        }      
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error filtering applications: " + e.getMessage());
        }
    }
   
    private void clearFilters() {
        cmbAppliedForFilter.setSelectedIndex(0);
        cmbStatusFilter.setSelectedIndex(0);
        txtSearch.setText("");
        loadInternData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInterns = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cmbStatusFilter = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        cmbAppliedForFilter = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Intern Application Form");

        tblInterns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Applicant", "Email", "Phone", "University", "Course", "Qualification", "Resume Path", "Applied For", "Date", "Status", "Interview Date", "Interview Notes", "Skills"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInterns.setColumnSelectionAllowed(true);
        tblInterns.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblInterns);
        tblInterns.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblInterns.getColumnModel().getColumnCount() > 0) {
            tblInterns.getColumnModel().getColumn(0).setResizable(false);
            tblInterns.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblInterns.getColumnModel().getColumn(1).setResizable(false);
            tblInterns.getColumnModel().getColumn(2).setResizable(false);
            tblInterns.getColumnModel().getColumn(3).setResizable(false);
            tblInterns.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblInterns.getColumnModel().getColumn(4).setResizable(false);
            tblInterns.getColumnModel().getColumn(5).setResizable(false);
            tblInterns.getColumnModel().getColumn(6).setResizable(false);
            tblInterns.getColumnModel().getColumn(6).setPreferredWidth(55);
            tblInterns.getColumnModel().getColumn(7).setResizable(false);
            tblInterns.getColumnModel().getColumn(8).setResizable(false);
            tblInterns.getColumnModel().getColumn(8).setPreferredWidth(55);
            tblInterns.getColumnModel().getColumn(9).setResizable(false);
            tblInterns.getColumnModel().getColumn(9).setPreferredWidth(40);
            tblInterns.getColumnModel().getColumn(10).setResizable(false);
            tblInterns.getColumnModel().getColumn(11).setResizable(false);
            tblInterns.getColumnModel().getColumn(11).setPreferredWidth(90);
            tblInterns.getColumnModel().getColumn(12).setResizable(false);
            tblInterns.getColumnModel().getColumn(13).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inquiry Panel"));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cmbStatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Statuses", "Received", "Reviewed", "Interviewed", "Accepted", "Rejected", "Hired" }));

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        cmbAppliedForFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Sectors", "Development", "Support", "Training", "General" }));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jButton1.setText("Clear Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(118, 118, 118)
                .addComponent(cmbAppliedForFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(cmbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter)
                    .addComponent(cmbAppliedForFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Intern Operation"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchData();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadInternData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        filterIntens();
    }//GEN-LAST:event_btnFilterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearFilters();
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbAppliedForFilter;
    private javax.swing.JComboBox<String> cmbStatusFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInterns;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
