package com.itsolutioncenter.forms;

import com.itsolutioncenter.config.AppConfig;
import com.itsolutioncenter.model.Permission;
import com.itsolutioncenter.model.User;
import com.itsolutioncenter.service.UserService;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author Ahmad Shafiq Amiri
 */
public class Main_Form extends javax.swing.JFrame {
    private User currentUser;
    private Permission userpPermissions;
    public Main_Form() {
    }
    public Main_Form(User user)
    {
        this.currentUser=user;
        this.userpPermissions = UserService.getPermissions(user.getRole());
        setTitle("Main Form - " + user.getFullName() + " [" + user.getRole() + "]");
        initComponents();
        setLocationRelativeTo(null);
        applyPermissionsToMenu();
    }

       private void applyPermissionsToMenu() {
        // Check each menu item based on user permissions
        userMangMenuItem.setEnabled(userpPermissions.canManageUsers());

        // Hide entire menu if no items are accessible
        if(!userpPermissions.canManageUsers())
            menuBar.remove(financeMenu);

        menuBar.revalidate();
        menuBar.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MainDesktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        changePassMenuItem = new javax.swing.JMenuItem();
        userRightsMenuItem = new javax.swing.JMenuItem();
        userMangMenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        courseManagMenuItem = new javax.swing.JMenuItem();
        enrollmentFormMenuItemt = new javax.swing.JMenuItem();
        attendanceMenuItem = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        internManagMenuItem = new javax.swing.JMenuItem();
        internApplicationMenuItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        clientManagMenuItem = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        projectMangMenuItem = new javax.swing.JMenuItem();
        financeMenu = new javax.swing.JMenu();
        incomeMenuItem = new javax.swing.JMenuItem();
        expenseMenuItem = new javax.swing.JMenuItem();
        transactionReportMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        assetManagMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        reportGenMenuItem = new javax.swing.JMenuItem();
        financeReportMenuItem = new javax.swing.JMenuItem();
        supportReportMenuItem = new javax.swing.JMenuItem();
        courseReportMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        userMenualMenuItem = new javax.swing.JMenuItem();
        quickStartMenuItem = new javax.swing.JMenuItem();
        supportMenuItem = new javax.swing.JMenuItem();
        systemInfoMenuItem = new javax.swing.JMenuItem();
        shortcutMenuItem = new javax.swing.JMenuItem();
        faqMenuItem = new javax.swing.JMenuItem();
        troubleMenuItem = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 640));
        setSize(new java.awt.Dimension(700, 500));

        MainDesktop.setForeground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout MainDesktopLayout = new javax.swing.GroupLayout(MainDesktop);
        MainDesktop.setLayout(MainDesktopLayout);
        MainDesktopLayout.setHorizontalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        MainDesktopLayout.setVerticalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenu1.setMnemonic('F');
        jMenu1.setText("فایل");

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem28.setMnemonic('A');
        jMenuItem28.setText("معلومات برنامه");
        jMenuItem28.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem28);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setMnemonic('L');
        jMenuItem1.setText("خروج از برنامه");
        jMenuItem1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setMnemonic('x');
        jMenuItem9.setText("بستن برنامه");
        jMenuItem9.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        menuBar.add(jMenu1);

        userMenu.setMnemonic('U');
        userMenu.setText("کارکنان");

        changePassMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        changePassMenuItem.setMnemonic('P');
        changePassMenuItem.setText("تغییر رمز");
        changePassMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        changePassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(changePassMenuItem);

        userRightsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        userRightsMenuItem.setMnemonic('R');
        userRightsMenuItem.setText("صلاحیت کاربران");
        userRightsMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        userRightsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRightsMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userRightsMenuItem);

        userMangMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        userMangMenuItem.setMnemonic('M');
        userMangMenuItem.setText("مدیریت کارکنان");
        userMangMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        userMangMenuItem.setEnabled(true);
        userMangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMangMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(userMangMenuItem);

        menuBar.add(userMenu);

        jMenu5.setMnemonic('C');
        jMenu5.setText("کورس");

        courseManagMenuItem.setMnemonic('M');
        courseManagMenuItem.setText("مدیریت کورس");
        courseManagMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        courseManagMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseManagMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(courseManagMenuItem);

        enrollmentFormMenuItemt.setMnemonic('E');
        enrollmentFormMenuItemt.setText("شمولیت");
        enrollmentFormMenuItemt.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        enrollmentFormMenuItemt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentFormMenuItemtActionPerformed(evt);
            }
        });
        jMenu5.add(enrollmentFormMenuItemt);

        attendanceMenuItem.setText("حاضری");
        attendanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(attendanceMenuItem);

        menuBar.add(jMenu5);

        jMenu8.setMnemonic('I');
        jMenu8.setText("کارآموز");

        internManagMenuItem.setMnemonic('n');
        internManagMenuItem.setText("مدیریت کارآموزان");
        internManagMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenu8.add(internManagMenuItem);

        internApplicationMenuItem.setMnemonic('c');
        internApplicationMenuItem.setText("فورم درخواست");
        internApplicationMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        internApplicationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internApplicationMenuItemActionPerformed(evt);
            }
        });
        jMenu8.add(internApplicationMenuItem);

        menuBar.add(jMenu8);

        jMenu6.setMnemonic('n');
        jMenu6.setText("مشتری");

        clientManagMenuItem.setMnemonic('l');
        clientManagMenuItem.setText("مدیریت مشتریان");
        clientManagMenuItem.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        clientManagMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientManagMenuItemActionPerformed(evt);
            }
        });
        jMenu6.add(clientManagMenuItem);

        menuBar.add(jMenu6);

        jMenu10.setMnemonic('P');
        jMenu10.setText("پروژه و پشتیبانی");

        projectMangMenuItem.setMnemonic('j');
        projectMangMenuItem.setText("Project Management Form");
        projectMangMenuItem.setToolTipText("");
        projectMangMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectMangMenuItemActionPerformed(evt);
            }
        });
        jMenu10.add(projectMangMenuItem);

        menuBar.add(jMenu10);

        financeMenu.setMnemonic('n');
        financeMenu.setText("مالی");

        incomeMenuItem.setMnemonic('o');
        incomeMenuItem.setText("Income Form");
        incomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeMenuItemActionPerformed(evt);
            }
        });
        financeMenu.add(incomeMenuItem);

        expenseMenuItem.setMnemonic('x');
        expenseMenuItem.setText("Expense Form");
        expenseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseMenuItemActionPerformed(evt);
            }
        });
        financeMenu.add(expenseMenuItem);

        transactionReportMenuItem.setMnemonic('T');
        transactionReportMenuItem.setText("Transaction Report Form");
        financeMenu.add(transactionReportMenuItem);
        financeMenu.add(jSeparator2);

        assetManagMenuItem.setMnemonic('A');
        assetManagMenuItem.setText("Asset Management Form");
        assetManagMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetManagMenuItemActionPerformed(evt);
            }
        });
        financeMenu.add(assetManagMenuItem);

        menuBar.add(financeMenu);

        reportsMenu.setMnemonic('R');
        reportsMenu.setText("گزارش");

        reportGenMenuItem.setMnemonic('G');
        reportGenMenuItem.setText("Report Generator Form");
        reportGenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportGenMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(reportGenMenuItem);

        financeReportMenuItem.setMnemonic('F');
        financeReportMenuItem.setText("Financial Report");
        financeReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeReportMenuItemActionPerformed(evt);
            }
        });
        reportsMenu.add(financeReportMenuItem);

        supportReportMenuItem.setMnemonic('S');
        supportReportMenuItem.setText("Support Report");
        reportsMenu.add(supportReportMenuItem);

        courseReportMenuItem.setMnemonic('C');
        courseReportMenuItem.setText("Course Report");
        reportsMenu.add(courseReportMenuItem);

        menuBar.add(reportsMenu);

        jMenu2.setText("کمک");

        helpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpMenuItem.setText("Help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(helpMenuItem);

        userMenualMenuItem.setText("User Manual");
        userMenualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMenualMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(userMenualMenuItem);

        quickStartMenuItem.setText("Quick Start");
        quickStartMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickStartMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(quickStartMenuItem);

        supportMenuItem.setText("Support");
        supportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(supportMenuItem);

        systemInfoMenuItem.setText("System Info");
        systemInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemInfoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(systemInfoMenuItem);

        shortcutMenuItem.setText("Shortcuts");
        shortcutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(shortcutMenuItem);

        faqMenuItem.setText("FAQs");
        faqMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faqMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(faqMenuItem);

        troubleMenuItem.setText("Troubleshooting");
        troubleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troubleMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(troubleMenuItem);

        menuBar.add(jMenu2);

        menuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        logout();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void changePassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassMenuItemActionPerformed
        ChangePasswordForm cpf=new ChangePasswordForm(currentUser,userpPermissions);
        MainDesktop.add(cpf);
        cpf.setVisible(true);
    }//GEN-LAST:event_changePassMenuItemActionPerformed

    private void userRightsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRightsMenuItemActionPerformed
         UserRightsForm urf=new UserRightsForm(currentUser,userpPermissions);
       MainDesktop.add(urf);
       urf.setVisible(true);   
    }//GEN-LAST:event_userRightsMenuItemActionPerformed

    private void userMangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMangMenuItemActionPerformed
        UserManagementForm umf=new UserManagementForm(currentUser,userpPermissions);
        MainDesktop.add(umf);
        umf.setVisible(true);
    }//GEN-LAST:event_userMangMenuItemActionPerformed

    private void reportGenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportGenMenuItemActionPerformed
        ReportForm rForm=new ReportForm();
        MainDesktop.add(rForm);
        rForm.setVisible(true);
    }//GEN-LAST:event_reportGenMenuItemActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //this.dispose();
      System.exit(0);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
         //JOptionPane.showMessageDialog(null, AppConfig.getAppInfo());
         JOptionPane.showMessageDialog(null, AppConfig.getAppInfo(), "Application Information",JRootPane.INFORMATION_DIALOG);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void internApplicationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internApplicationMenuItemActionPerformed
        InternApplicationForm iaf=new InternApplicationForm();
        MainDesktop.add(iaf);
        iaf.setVisible(true);
    }//GEN-LAST:event_internApplicationMenuItemActionPerformed

    private void courseManagMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseManagMenuItemActionPerformed
        CourseManagementForm cmf=new CourseManagementForm(currentUser,userpPermissions);
        MainDesktop.add(cmf);
        cmf.setVisible(true);
    }//GEN-LAST:event_courseManagMenuItemActionPerformed

    private void enrollmentFormMenuItemtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentFormMenuItemtActionPerformed
    //    if(canAccess("COURSE", "CourseForm", "view")){
        CourseEnrollmentForm cef=new CourseEnrollmentForm(currentUser,userpPermissions);
        MainDesktop.add(cef);
        cef.setVisible(true);
        //    } else
      //      showAccessDenied("Course Enrollment");
    }//GEN-LAST:event_enrollmentFormMenuItemtActionPerformed

    private void assetManagMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetManagMenuItemActionPerformed
    AssetManagementForm asmf=new AssetManagementForm();
    MainDesktop.add(asmf);
    asmf.setVisible(true);
    }//GEN-LAST:event_assetManagMenuItemActionPerformed
 
    private void userMenualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMenualMenuItemActionPerformed
        HelpMenu.showUserManual();
        
    }//GEN-LAST:event_userMenualMenuItemActionPerformed

    private void quickStartMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickStartMenuItemActionPerformed
        HelpMenu.showQuickStart();
    }//GEN-LAST:event_quickStartMenuItemActionPerformed

    private void supportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportMenuItemActionPerformed
        HelpMenu.contactSupport();
    }//GEN-LAST:event_supportMenuItemActionPerformed

    private void systemInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemInfoMenuItemActionPerformed
        HelpMenu.showSystemInfo();
    }//GEN-LAST:event_systemInfoMenuItemActionPerformed

    private void shortcutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcutMenuItemActionPerformed
        HelpMenu.showShortcuts();
    }//GEN-LAST:event_shortcutMenuItemActionPerformed

    private void faqMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faqMenuItemActionPerformed
        HelpMenu.showFAQ();
    }//GEN-LAST:event_faqMenuItemActionPerformed

    private void troubleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troubleMenuItemActionPerformed
        HelpMenu.showTroubleshooting();
    }//GEN-LAST:event_troubleMenuItemActionPerformed

    private void helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItemActionPerformed
    HelpForm help=new HelpForm("");
    help.setVisible(true);
  
    }//GEN-LAST:event_helpMenuItemActionPerformed

    private void clientManagMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientManagMenuItemActionPerformed
        ClientManagementForm cmf=new ClientManagementForm();
        MainDesktop.add(cmf);
        cmf.setVisible(true);
    }//GEN-LAST:event_clientManagMenuItemActionPerformed

    private void attendanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceMenuItemActionPerformed
    AttendanceForm atf=new AttendanceForm();
    MainDesktop.add(atf);
    atf.setVisible(true);
    }//GEN-LAST:event_attendanceMenuItemActionPerformed

    private void projectMangMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectMangMenuItemActionPerformed
         ProjectManagementForm pmf=new ProjectManagementForm();
        MainDesktop.add(pmf);
        pmf.setVisible(true);
    }//GEN-LAST:event_projectMangMenuItemActionPerformed

    private void financeReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeReportMenuItemActionPerformed
       if(!userpPermissions.canManageUsers())
       {
           showAccessDenied("Finance Report"); 
       }
    }//GEN-LAST:event_financeReportMenuItemActionPerformed

    private void incomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeMenuItemActionPerformed
        IncomeForm inform=new IncomeForm();
        MainDesktop.add(inform);
        inform.setVisible(true);
    }//GEN-LAST:event_incomeMenuItemActionPerformed

    private void expenseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseMenuItemActionPerformed
        ExpenseForm eform=new ExpenseForm();
        MainDesktop.add(eform);
        eform.setVisible(true);
    }//GEN-LAST:event_expenseMenuItemActionPerformed
    private void showAccessDenied(String module) {
        JOptionPane.showMessageDialog(this,
            "Access Denied!\n\nYou don't have permission to access " + module + ".\n" +
            "Please contact your administrator if you need access.",
            "Access Denied",
            JOptionPane.WARNING_MESSAGE);
    }
    private void logout() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            
            new LoginForm().setVisible(true);
            this.dispose();
            
        }
    }
private void showSimpleHelp() {
    String helpText = """
        IT SOLUTION CENTER MIS - HELP
       
        For assistance, please contact:
        Email: support@itsolutioncenter.com
        Phone: +93(0)799063252
       
        Common Tasks:
        1. Add User: Manage → User Management → Add New
        2. Create Ticket: Manage → Support Tickets → New Ticket
        3. Generate Report: Reports → Select Report Type
       
        Press F1 in any form for context-specific help.
        """;
   
    JOptionPane.showMessageDialog(this, helpText, "Help", JOptionPane.INFORMATION_MESSAGE);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainDesktop;
    private javax.swing.JMenuItem assetManagMenuItem;
    private javax.swing.JMenuItem attendanceMenuItem;
    private javax.swing.JMenuItem changePassMenuItem;
    private javax.swing.JMenuItem clientManagMenuItem;
    private javax.swing.JMenuItem courseManagMenuItem;
    private javax.swing.JMenuItem courseReportMenuItem;
    private javax.swing.JMenuItem enrollmentFormMenuItemt;
    private javax.swing.JMenuItem expenseMenuItem;
    private javax.swing.JMenuItem faqMenuItem;
    private javax.swing.JMenu financeMenu;
    private javax.swing.JMenuItem financeReportMenuItem;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenuItem incomeMenuItem;
    private javax.swing.JMenuItem internApplicationMenuItem;
    private javax.swing.JMenuItem internManagMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem projectMangMenuItem;
    private javax.swing.JMenuItem quickStartMenuItem;
    private javax.swing.JMenuItem reportGenMenuItem;
    private javax.swing.JMenu reportsMenu;
    private javax.swing.JMenuItem shortcutMenuItem;
    private javax.swing.JMenuItem supportMenuItem;
    private javax.swing.JMenuItem supportReportMenuItem;
    private javax.swing.JMenuItem systemInfoMenuItem;
    private javax.swing.JMenuItem transactionReportMenuItem;
    private javax.swing.JMenuItem troubleMenuItem;
    private javax.swing.JMenuItem userMangMenuItem;
    private javax.swing.JMenu userMenu;
    private javax.swing.JMenuItem userMenualMenuItem;
    private javax.swing.JMenuItem userRightsMenuItem;
    // End of variables declaration//GEN-END:variables
}
