package com.itsolutioncenter.forms;

import com.itsolutioncenter.model.Student;
import com.itsolutioncenter.util.ImageUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.function.Consumer;

/**
 * @author Administrator
 */
public class StudentCardPanel extends javax.swing.JPanel {

    private static final Color DEFAULT_BORDER = new Color(0, 0, 0);
    private static final Color HOVER_BORDER = new Color(51, 122, 183);

    private final Student student;

    /**
     * @param student    the student this card displays
     * @param onSelect   called with this card's student when the card is clicked
     */
    public StudentCardPanel(Student student, Consumer<Student> onSelect) {
        initComponents();
        this.student = student;
        bind(student);
        wireInteraction(onSelect);
    }

    /** Populates the card's labels and image from the given student. Kept separate
     *  from the constructor so a card could be re-bound to a new student later
     *  (e.g. for panel recycling) without rebuilding the UI. */
    private void bind(Student student) {
        idLabel.setText("ID: " + student.getStudentId());
        nameLabel.setText("Name: " + student.getFullName());
        courseLabel.setText("Father Name: " + student.getFathername());
        emailLabel.setText("Email: " + student.getEmail());

        ImageIcon icon = ImageUtils.loadOrDefault(student.getImagePath());
        imageLabel.setIcon(ImageUtils.resizeImage(icon, 150, 150));
    }

    /** Click + hover behavior lives in one place so every card behaves identically. */
    private void wireInteraction(Consumer<Student> onSelect) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        setBorder(BorderFactory.createLineBorder(DEFAULT_BORDER));

        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (onSelect != null) {
                    onSelect.accept(student);
                }
            }

            @Override
            public void mouseEntered(MouseEvent evt) {
                setBorder(BorderFactory.createLineBorder(HOVER_BORDER, 2));
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                setBorder(BorderFactory.createLineBorder(DEFAULT_BORDER, 1));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(200, 250));
        setLayout(new java.awt.BorderLayout());

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 5, 5));
        jPanel1.add(nameLabel);
        jPanel1.add(idLabel);
        jPanel1.add(emailLabel);
        jPanel1.add(courseLabel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
