package com.itsolutioncenter.forms;

import com.itsolutioncenter.dao.DatabaseManager;
import com.itsolutioncenter.model.Student;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 * @author Administrator
 */
public class StudentListForm extends JInternalFrame {
    private final DatabaseManager dbManager = DatabaseManager.getInstance();

    public StudentListForm() {
        initComponents();
        // Wired here (not inside initComponents) so the generated code block stays untouched.
        btnRefreshList.addActionListener(e -> loadStudents());
        loadStudents();
    }

    private void loadStudents() {
        btnRefreshList.setEnabled(false);
        studentGridPanel.removeAll();
        studentGridPanel.revalidate();
        studentGridPanel.repaint();

        new SwingWorker<List<Student>, Void>() {
            @Override
            protected List<Student> doInBackground() {
                return getAllStudents();
            }

            @Override
            protected void done() {
                try {
                    for (Student student : get()) {
                        // One shared method reference instead of a fresh Runnable per card.
                        studentGridPanel.add(new StudentCardPanel(student, StudentListForm.this::showStudentDetails));
                    }
                    studentGridPanel.revalidate();
                    studentGridPanel.repaint();
                } catch (Exception e) {
                    showError("Failed to render student UI: " + e.getMessage());
                } finally {
                    btnRefreshList.setEnabled(true);
                }
            }
        }.execute();
    }

    private List<Student> getAllStudents() {
        List<Student> students = new ArrayList<>();
        String query = "SELECT * FROM students ORDER BY student_id";

        try (ResultSet rs = dbManager.executeSimpleQuery(query)) { // Try-with-resources avoids leaks
            while (rs.next()) {
                students.add(new Student(
                    rs.getString("student_id"), rs.getString("full_name"),
                    rs.getString("father_name"), rs.getString("email"),
                    rs.getString("phone"), rs.getString("image_path")
                ));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            showError("Error loading students: " + e.getMessage());
        }
        return students;
    }

    private void showStudentDetails(Student student) {
        Window parent = SwingUtilities.getWindowAncestor(this);
        Frame frame = (parent instanceof Frame f) ? f : null; // Pattern matching syntax
        new StudentDetailsDialog(frame, true, student).setVisible(true);
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        studentGridPanel = new javax.swing.JPanel();
        btnRefreshList = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Student List Form");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setVisible(true);

        lblTitle.setFont(new java.awt.Font("B Titr", 1, 12)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle.setText("فهرست شاگردان");
        getContentPane().add(lblTitle, java.awt.BorderLayout.PAGE_START);

        studentGridPanel.setLayout(new java.awt.GridLayout(0, 4, 10, 10));
        scrollPane.setViewportView(studentGridPanel);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        btnRefreshList.setText("Refresh List");
        getContentPane().add(btnRefreshList, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel studentGridPanel;
    // End of variables declaration//GEN-END:variables
}
