package com.itsolutioncenter.forms;

import com.itsolutioncenter.model.Student;
import com.itsolutioncenter.util.ImageUtils;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 * @author Administrator
 */
public class StudentDetailsDialog extends javax.swing.JDialog {

    /**
     * Creates new form StudentDetailsDialog
     */
    public StudentDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        wireCloseOnEscape();
    }

    public StudentDetailsDialog(java.awt.Frame parent, boolean modal, Student student) {
        super(parent, modal);
        initComponents();
        wireCloseOnEscape();
        bind(student);
        setLocationRelativeTo(parent);
    }

    /** Populates the dialog from the given student. Separated from the constructor
     *  so the same dialog instance could be re-shown for a different student later. */
    private void bind(Student student) {
        setTitle("Student Details - " + student.getFullName());

        idLabel.setText(student.getStudentId());
        nameLabel.setText(student.getFullName());
        fatherNameLabel.setText(student.getFathername());
        emailLabel.setText(student.getEmail());
        phoneLabel.setText(student.getPhone());

        ImageIcon icon = ImageUtils.loadOrDefault(student.getImagePath());
        imageLabel.setIcon(ImageUtils.resizeImage(icon, 200, 200));
        pack(); 
    }

    /** Lets the user dismiss the dialog with Esc, same as clicking Close. */
    private void wireCloseOnEscape() {
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        getRootPane().registerKeyboardAction(
                e -> dispose(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW
        );
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(imageLabel, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(idLabel);

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(nameLabel);

        fatherNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(fatherNameLabel);

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(emailLabel);

        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(phoneLabel);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);
        jPanel1.add(btnClose);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDetailsDialog dialog = new StudentDetailsDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    // End of variables declaration//GEN-END:variables
}
