
package com.itsolutioncenter.forms;

import com.itsolutioncenter.dao.DatabaseManager;
import com.itsolutioncenter.model.Permission;
import com.itsolutioncenter.model.User;
import com.itsolutioncenter.service.UserService;
import com.itsolutioncenter.util.Validator;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Ahmad Shafiq Amiri
 */
public class UserRightsForm extends javax.swing.JInternalFrame {
    private DatabaseManager dbManager=DatabaseManager.getInstance();
    private User currentUser;
    private UserService userService=new UserService();
    private Permission permissionService;
    private String query,username,role,password,hashPassword;
    private ResultSet rs;
    private int userID;
    private boolean isActive;
    public UserRightsForm() {    }
    public UserRightsForm(User user, Permission permissionService)
    {
        this.currentUser=user;
        this.permissionService=permissionService; 
        this.currentUser.setUserId(user.getUserId());
        this.currentUser.setUsername(user.getUsername());
        this.currentUser.setFullName(user.getFullName());
        this.currentUser.setRole(user.getRole());
        initComponents();
        lblUser.setText("Full Name: "+user.getFullName());
        lblRole.setText("Role: "+user.getRole());
        btnGroup.add(rdbActive); 
        btnGroup.add(rdbDeactive);
        loadUserRights();
        if(!permissionService.canManageUsers())tbPanUserPerm.remove(1);
        loadUserNames();
    }
    private void loadUserRights()
    {
        lblView.setText("Can View Forms: "+String.valueOf(this.permissionService.canView()));
        lblAdd.setText("Can Add Data: "+String.valueOf(this.permissionService.canAdd()));
        lblEdit.setText("Can Edit Data: "+String.valueOf(this.permissionService.canEdit()));
        lblDelete.setText("Can Delete Data: "+String.valueOf(this.permissionService.canDelete()));
        lblReport.setText("Can Report Data: "+String.valueOf(this.permissionService.canReport()));
        lblExport.setText("Can Export Data: "+String.valueOf(this.permissionService.canExport()));
        lblManage.setText("Can Manage Users: "+String.valueOf(this.permissionService.canManageUsers()));
        
    }
    private void loadUserNames ()
    {
    query="Select username from users order by user_id";
//    rs=DatabaseManager.executeSimpleQuery(query);
cmbUsername.removeAllItems();
cmbUsername.addItem("-- Username --");
List<Map<String,Object>>usernames=dbManager.getAllUsers1();
for(Map<String,Object>users:usernames){
    cmbUsername.addItem(users.get("username").toString());
}
//  while(rs.next())
{
        //cmbUsername.addItem(rs.getString("username"));
    }
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        tbPanUserPerm = new javax.swing.JTabbedPane();
        pnlPermission = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblExport = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        pnlEdit = new javax.swing.JPanel();
        cmbUsername = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        rdbActive = new javax.swing.JRadioButton();
        rdbDeactive = new javax.swing.JRadioButton();
        btnEditUserType = new javax.swing.JButton();
        btnActivateDeactivate = new javax.swing.JButton();
        chkView = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        chkAdd = new javax.swing.JCheckBox();
        chkEdit = new javax.swing.JCheckBox();
        chkExport = new javax.swing.JCheckBox();
        chkManage = new javax.swing.JCheckBox();
        chkDelete = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        chkReport = new javax.swing.JCheckBox();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setTitle("صلاحیت های استفاده کننده");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Users Folder.png"))); // NOI18N

        lblEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEdit.setText("Edit");

        lblView.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblView.setText("View");

        lblUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUser.setText("Fulll Name:");

        lblDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDelete.setText("Delete");

        lblRole.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRole.setText("User Role:");

        lblAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAdd.setText("Add");

        lblExport.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblExport.setText("Export");

        lblManage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblManage.setText("Manage");

        jLabel1.setText("The User Rights of Current User is as Follow!");
        jLabel1.setToolTipText("");

        lblReport.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReport.setText("Report");

        javax.swing.GroupLayout pnlPermissionLayout = new javax.swing.GroupLayout(pnlPermission);
        pnlPermission.setLayout(pnlPermissionLayout);
        pnlPermissionLayout.setHorizontalGroup(
            pnlPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlPermissionLayout.createSequentialGroup()
                .addGroup(pnlPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPermissionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole)
                            .addComponent(lblEdit)
                            .addComponent(lblUser)
                            .addComponent(lblDelete)
                            .addComponent(lblView)
                            .addComponent(lblAdd)
                            .addComponent(lblExport)
                            .addComponent(lblManage)))
                    .addGroup(pnlPermissionLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addGroup(pnlPermissionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblReport)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlPermissionLayout.setVerticalGroup(
            pnlPermissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPermissionLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManage)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        tbPanUserPerm.addTab("User Permissions", pnlPermission);

        cmbUsername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- User Name --" }));
        cmbUsername.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUsernameItemStateChanged(evt);
            }
        });

        jLabel2.setText("User Name:");

        jLabel3.setText("User Type:");

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- User Type --", "Admin", "Manager", "Employee", "Intern", "Instructor" }));

        rdbActive.setText("Active");

        rdbDeactive.setText("Deactive");

        btnEditUserType.setText("Change User Type");
        btnEditUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserTypeActionPerformed(evt);
            }
        });

        btnActivateDeactivate.setText("Active/Deactive User");
        btnActivateDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateDeactivateActionPerformed(evt);
            }
        });

        chkView.setText("View");

        chkAdd.setText("Add");

        chkEdit.setText("Edit");

        chkExport.setText("Export Data");

        chkManage.setText("Manage Users");

        chkDelete.setText("Delete");

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        jLabel4.setText("Password:");

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        chkReport.setText("Report Data");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(chkView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkAdd)
                                .addGap(18, 18, 18)
                                .addComponent(chkEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDelete))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(chkReport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkExport)
                                .addGap(18, 18, 18)
                                .addComponent(chkManage)))
                        .addContainerGap(161, Short.MAX_VALUE))
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(rdbActive)
                                .addGap(18, 18, 18)
                                .addComponent(rdbDeactive))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                                .addComponent(btnRefresh)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActivateDeactivate)
                                    .addComponent(btnEditUserType))
                                .addGap(13, 13, 13))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(btnChangePassword)
                                .addContainerGap())))))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditUserType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbActive)
                    .addComponent(rdbDeactive)
                    .addComponent(btnActivateDeactivate))
                .addGap(11, 11, 11)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnChangePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkView)
                    .addComponent(chkAdd)
                    .addComponent(chkEdit)
                    .addComponent(chkDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkManage)
                    .addComponent(chkExport)
                    .addComponent(chkReport))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tbPanUserPerm.addTab("Edit Permissions", pnlEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbPanUserPerm, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbPanUserPerm, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsernameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUsernameItemStateChanged
    username=(String)cmbUsername.getSelectedItem();
   query="Select * from users where username='"+username+"'";
    try
    {
        List<Map<String,Object>> Names=dbManager.select(query);
        for(Map<String,Object>usernames:Names){
        cmbUserType.setSelectedItem(usernames.get("role"));
       isActive=(boolean)usernames.get("is_active");
       if(isActive)rdbActive.setSelected(true);else rdbDeactive.setSelected(true);
        }
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, "Users Data Couldn't Load");
    }
   if(cmbUsername.getSelectedIndex()>0)
   {
    username=(String)cmbUsername.getSelectedItem();
        User user=dbManager.getUserByUsername(username);
        role=user.getRole();
        permissionService=UserService.getPermissions(role);
        if(permissionService.canView())chkView.setSelected(true);else chkView.setSelected(false);
        if(permissionService.canAdd())chkAdd.setSelected(true);else chkAdd.setSelected(false);
        if(permissionService.canEdit())chkEdit.setSelected(true); else chkEdit.setSelected(false);
        if(permissionService.canDelete())chkDelete.setSelected(true); else chkDelete.setSelected(false);
        if(permissionService.canReport())chkReport.setSelected(true); else chkReport.setSelected(false);
        if(permissionService.canExport())chkExport.setSelected(true); else chkExport.setSelected(false);
        if(permissionService.canManageUsers())chkManage.setSelected(true); else chkManage.setSelected(false);
   }
    }//GEN-LAST:event_cmbUsernameItemStateChanged
    private void changeUserRole()
    {
        if(cmbUserType.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "Please select user type");
            return;
        }
        role=(String)cmbUserType.getSelectedItem();
        username=(String)cmbUsername.getSelectedItem();
        int change=userService.changeUserType(role, username);
        if(change>0)
        {
            JOptionPane.showMessageDialog(this, "User Type changed successfully");  }
        else
        {
            JOptionPane.showMessageDialog(this, "Error in changing user type ");
        }    
    }
    private void activate_deactivateUser()
    {
        username=(String)cmbUsername.getSelectedItem();
        if(rdbActive.isSelected())
       {
           userService.activateUser(username);
           JOptionPane.showMessageDialog(this, "User Activated Successfully");
       }
        if(rdbDeactive.isSelected())
        {
            userService.deactivateUser(username);
            JOptionPane.showMessageDialog(this, "User Deactivated Successfully");
        }
    }
    private void changePassword()
    {
        if(cmbUsername.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "Please select username");
            return;
        }
        if(!Validator.validateRequired(txtPassword, "Password"))
        {
            return;
        }
        password=new String(txtPassword.getPassword());
        if(!Validator.isLengthValid(password, 5, 10))
        {
            JOptionPane.showMessageDialog(this, "Password must be at least 5 or maximum 10 characters",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocusInWindow();
            txtPassword.setBackground(new Color(255,230,230));
            txtPassword.setForeground(Color.red);
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.yellow,2));
            return;
        }
        hashPassword=BCrypt.hashpw(password, BCrypt.gensalt());
        int userID = 0;
             try
             {
                 List<Map<String,Object>> users=dbManager.query("select user_id from users where username=?", username);
                 for(Map<String,Object> s: users){
                 userID=Integer.parseInt(s.get("user_id").toString());}
             }catch(SQLException e)
             {
                 JOptionPane.showMessageDialog(null, e.getMessage());
             }
             if(dbManager.updatePassword(userID, hashPassword))
             {
                 JOptionPane.showMessageDialog(this, "Password updated successfully");
                 txtPassword.setText("");
             }else
             {
                 JOptionPane.showMessageDialog(this, "Error in updating password");
             }
    }
    private void btnEditUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserTypeActionPerformed
        changeUserRole();
    }//GEN-LAST:event_btnEditUserTypeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
            cmbUsername.setSelectedIndex(0);
            cmbUserType.setSelectedIndex(0);
            btnGroup.clearSelection();
            txtPassword.setText("");
            chkAdd.setSelected(false);
            chkDelete.setSelected(false);
            chkEdit.setSelected(false);
            chkExport.setSelected(false);
            chkReport.setSelected(false);
            chkManage.setSelected(false);
            chkView.setSelected(false); 
    }//GEN-LAST:event_btnRefreshActionPerformed
    
    private void btnActivateDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateDeactivateActionPerformed
        activate_deactivateUser();
    }//GEN-LAST:event_btnActivateDeactivateActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        changePassword();
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
       txtPassword.setBackground(Color.WHITE);
        txtPassword.setBorder(UIManager.getBorder("TextField.border"));
        txtPassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPasswordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateDeactivate;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnEditUserType;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JCheckBox chkAdd;
    private javax.swing.JCheckBox chkDelete;
    private javax.swing.JCheckBox chkEdit;
    private javax.swing.JCheckBox chkExport;
    private javax.swing.JCheckBox chkManage;
    private javax.swing.JCheckBox chkReport;
    private javax.swing.JCheckBox chkView;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JComboBox<String> cmbUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblExport;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblView;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlPermission;
    private javax.swing.JRadioButton rdbActive;
    private javax.swing.JRadioButton rdbDeactive;
    private javax.swing.JTabbedPane tbPanUserPerm;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
